---
deployment:
  tasks:
    - export DEPLOYPATH=/home/your_cpanel_username/public_html/
    - /bin/rsync -av --exclude='.git' --exclude='storage/logs/*' --exclude='.env' backend/ $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
